name: Linting

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: LaTeX
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: LaTeX linter (chktex)
        uses: j2kun/chktex-action@1.0.3
